[project]
name = "neuraltranslate-nahuatl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate<1.8.0",
    "datasets>=3.6.0",
    "unsloth>=2025.6.2",
    "wandb>=0.20.1",
    "transformers<=4.51.3",
]
